import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/_components/navbar/Navbar";
import { Suspense } from "react";
import { getPageStructure } from "@/lib/getPageStructure";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const categories = await getPageStructure();
    return (
        <html lang="en">
            <body>
                <main>
                    <Suspense fallback={<div>Loading...</div>}>
                        <Navbar categories={categories} />
                    </Suspense>
                    {children}
                </main>
            </body>
        </html>
    );
}
